version: '3.4'

services:
  dapr.eshop.order:
    image: dapreshoporder:dev
    container_name: dapr.eshop.order
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "dapr.eshop.order"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\toanduong\Documents\Projects\microservices\dapr\dapr-demo\backends\dapr.eshop.services\dapr.eshop.order:/app
      - C:\Users\toanduong\Documents\Projects\microservices\dapr\dapr-demo\backends\dapr.eshop.services:/src
      - C:\Users\toanduong\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\toanduong\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/dapr.eshop.order.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  dapr.eshop.product:
    image: dapreshopproduct:dev
    container_name: dapr.eshop.product
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "dapr.eshop.product"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\toanduong\Documents\Projects\microservices\dapr\dapr-demo\backends\dapr.eshop.services\dapr.eshop.product:/app
      - C:\Users\toanduong\Documents\Projects\microservices\dapr\dapr-demo\backends\dapr.eshop.services:/src
      - C:\Users\toanduong\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\toanduong\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/dapr.eshop.product.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
